version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: LugininaV-netology-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - LugininaV-my-netology-hw
volumes:
  prometheus-data:
networks:
  LugininaV-my-netology-hw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
